// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
<<<<<<< HEAD:CSharpAutomationFramework.API/Features/TCRS02_PostRequests.feature.cs
namespace CSharpAutomationFramework.API.Features
=======
namespace CSharpAutomationFramework.Selenium
>>>>>>> main:CSharpAutomationFramework/Selenium/TC01_DriverNavigation.feature.cs
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("TC01_DriverNavigation")]
    public partial class TC01_DriverNavigationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "TC01_DriverNavigation.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
<<<<<<< HEAD:CSharpAutomationFramework.API/Features/TCRS02_PostRequests.feature.cs
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "TCRS02_PostRequests", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
=======
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Selenium", "TC01_DriverNavigation", "This feature goes through using the navigation method of Selenium", ProgrammingLanguage.CSharp, featureTags);
>>>>>>> main:CSharpAutomationFramework/Selenium/TC01_DriverNavigation.feature.cs
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
<<<<<<< HEAD:CSharpAutomationFramework/Selenium/TC01_DriverNavigation.feature.cs
        [NUnit.Framework.DescriptionAttribute("Moving driver to a website")]
        [NUnit.Framework.CategoryAttribute("Selenium")]
        public void MovingDriverToAWebsite()
        {
            string[] tagsOfScenario = new string[] {
                    "Selenium"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Moving driver to a website", null, tagsOfScenario, argumentsOfScenario, featureTags);
=======
        [NUnit.Framework.DescriptionAttribute("[A user creates an entry using a post request]")]
        [NUnit.Framework.CategoryAttribute("RestSharp")]
        [NUnit.Framework.TestCaseAttribute("Employee1", "SoftwareEngineer", null)]
        public void AUserCreatesAnEntryUsingAPostRequest(string employee_Name, string designation, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RestSharp"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Employee_name", employee_Name);
            argumentsOfScenario.Add("Designation", designation);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[A user creates an entry using a post request]", null, tagsOfScenario, argumentsOfScenario, featureTags);
>>>>>>> d165a4a9d70e890ba9e62d3c2390f0f37ee961fc:CSharpAutomationFramework/cucumber.steps/Features/RestSharp/TCRS02_PostRequests.feature.cs
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
<<<<<<< HEAD:CSharpAutomationFramework/Selenium/TC01_DriverNavigation.feature.cs
 testRunner.Given("I have a browser driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
=======
    testRunner.Given(string.Format("[I create a post request with {0} and {1}]", employee_Name, designation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
>>>>>>> d165a4a9d70e890ba9e62d3c2390f0f37ee961fc:CSharpAutomationFramework/cucumber.steps/Features/RestSharp/TCRS02_PostRequests.feature.cs
#line hidden
#line 8
 testRunner.When("I use the Navigate method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 9
 testRunner.Then("The correct page will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
